<?php
/*Active*/
$save_disabled='disabled="disabled"';
$print_or_post_disabled='';
$post_disabled='';
$unpost_disabled='disabled="disabled"';
$re_print_disabled='disabled="disabled"';
$cancel_disabled='';
$remove_fn_disabled='disabled="disabled"';
$force_post_disabled='';
$print_jli_aai_disabled='disabled="disabled"';
$print_pcv_per_jo_disabled='';
$validate_disabled='disabled="disabled"';
$unvalidate_disabled='disabled="disabled"';
$force_validate_disabled='disabled="disabled"';
$add_jo_disabled='';
$add_disabled='';
$delete_disabled='';
$view_tariff_disabled='';
$hide_column='';
?>
